# Generated by Django 6.0.2 on 2026-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price_per_month',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='property_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('car', 'Car'), ('tool', 'Tool'), ('equipment', 'Equipment')], default='car', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
