# Generated by Django 6.0.2 on 2026-03-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_listing_price_per_hour_alter_listing_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='body_style',
            field=models.CharField(default='Sedan', help_text='Shown on cards (e.g. Luxury, SUV, Bakkie).', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=32),
        ),
        migrations.AddField(
            model_name='listing',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Optional hero image when no uploaded ListingImage exists.', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='seats',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(default='Automatic', max_length=32),
        ),
    ]
