# Generated by Django 6.0.2 on 2026-03-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listing_body_style_listing_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', help_text='Admin approval before a listing appears in browse/search.', max_length=20),
        ),
    ]
