"""
Django settings for yourstorent_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path
import os
import cloudinary
import cloudinary.uploader
import cloudinary.api
# import cloudinary.uploader
# import cloudinary.api

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv:
    load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^nomskov6exp@su@ponl_9ns021i4s5*$ywmsf=101zcfttv0+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



cloudinary.config(
    cloud_name = "dz0hjkwwm",
    api_key = "124816738685834",
    api_secret = "0FeZvy1_fO2xLp-Ekn4ZFSIhzOw"
)


ALLOWED_HOSTS = list(
    dict.fromkeys(
        [
            "127.0.0.1",
            "localhost",
            "testserver",
            "ytr-platform.onrender.com",
            *[h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()],
        ]
    )
)

STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_URL = '/static/'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework',
    'accounts',
    'vehicles',
    'bookings',
    'core',
    'users',
    'listings',
    'messaging',
    'cloudinary',
    'cloudinary_storage',
]

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'yourstorent_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # top-level templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.user_profile',
            ],
        },
    },
]


WSGI_APPLICATION = 'yourstorent_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Supabase / Postgres: set DATABASE_URL or discrete SUPABASE_DB_* / DB_* vars in .env (never commit secrets).
# Example DATABASE_URL:
#   postgresql://postgres:YOUR_PASSWORD@db.PROJECT_REF.supabase.co:5432/postgres?sslmode=require

def _postgres_options_for_host(host: str) -> dict:
    opts = {}
    if host and "supabase.co" in host:
        opts["sslmode"] = "require"
    return opts


_database_url = (os.environ.get("DATABASE_URL") or "").strip()

if _database_url:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(_database_url, conn_max_age=600),
    }
    _engine = DATABASES["default"].get("ENGINE", "")
    if "postgresql" in _engine:
        _opts = DATABASES["default"].setdefault("OPTIONS", {})
        _opts.setdefault("sslmode", "require")
elif os.environ.get("SUPABASE_DB_HOST") or os.environ.get("DB_HOST"):
    _host = (os.environ.get("SUPABASE_DB_HOST") or os.environ.get("DB_HOST") or "").strip()
    _name = os.environ.get("SUPABASE_DB_NAME") or os.environ.get("DB_NAME") or "postgres"
    _user = os.environ.get("SUPABASE_DB_USER") or os.environ.get("DB_USER") or "postgres"
    _password = os.environ.get("SUPABASE_DB_PASSWORD") or os.environ.get("DB_PASSWORD") or ""
    _port = os.environ.get("SUPABASE_DB_PORT") or os.environ.get("DB_PORT") or "5432"
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _name,
            "USER": _user,
            "PASSWORD": _password,
            "HOST": _host,
            "PORT": _port,
            "OPTIONS": _postgres_options_for_host(_host),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates', BASE_DIR]

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# Basic security hardening (safe for local dev + production toggles).
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if os.getenv("CSRF_TRUSTED_ORIGINS") else []
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Email / launch communication settings
BUSINESS_CONTACT_EMAIL = os.getenv("BUSINESS_CONTACT_EMAIL", "info@yourstorent.co.za")
# Inbound address for contact + feedback (client inbox); falls back to business email.
CLIENT_FEEDBACK_EMAIL = os.getenv("CLIENT_FEEDBACK_EMAIL", BUSINESS_CONTACT_EMAIL)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "info@yourstorent.co.za")
SERVER_EMAIL = DEFAULT_FROM_EMAIL
_EMAIL_PW = os.getenv("EMAIL_HOST_PASSWORD", "").strip()
if os.getenv("EMAIL_BACKEND"):
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
elif DEBUG and not _EMAIL_PW:
    # Local dev: log messages to console so forms still "work" without SMTP secrets.
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.hostinger.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "True").lower() == "true"
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "info@yourstorent.co.za")
EMAIL_HOST_PASSWORD = _EMAIL_PW

# --- Django Jazzmin (premium admin UI) ---
JAZZMIN_SETTINGS = {
    "site_title": "YTR Control",
    "site_header": "Yours To Rent",
    "site_brand": "Yours To Rent",
    "site_logo": "images/ytr-logo-reference.svg",
    "login_logo": "images/ytr-logo-reference.svg",
    "welcome_sign": "Fleet control — same brand system as the owner dashboard. Verify documents, manage listings, and monitor bookings.",
    "copyright": "Yours To Rent",
    "search_model": ["auth.User", "users.UserDocument", "core.Listing", "bookings.Booking"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Live site", "url": "/", "new_window": True},
        {"name": "Owner dashboard", "url": "/dashboard/", "new_window": True},
        {"name": "Browse commercial", "url": "/browse/?commercial=1", "new_window": True},
        {"name": "Verify documents", "url": "admin:users_userdocument_changelist"},
        {"name": "Notifications", "url": "admin:users_platformnotification_changelist"},
    ],
    "icons": {
        "auth.User": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
        "users.UserProfile": "fas fa-id-badge",
        "users.UserDocument": "fas fa-file-signature",
        "users.PlatformNotification": "fas fa-bullhorn",
        "users.UserNotificationRead": "fas fa-envelope-open-text",
        "core.Listing": "fas fa-car-side",
        "core.ListingImage": "fas fa-images",
        "bookings.Booking": "fas fa-calendar-check",
        "messaging.Message": "fas fa-comments",
        "sites.Site": "fas fa-globe",
    },
    "order_with_respect_to": [
        "auth",
        "users",
        "core",
        "bookings",
        "messaging",
        "sites",
        "account",
        "socialaccount",
    ],
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "admin/css/ytr_admin.css",
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-warning",
    "navbar": "navbar-dark navbar-warning",
    "no_navbar_border": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_flat_style": True,
    "sidebar_disable_expand": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

